# Generated by Django 4.1 on 2022-08-30 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ejercicio18', '0002_rename_familiar2_familiar_delete_familiar1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familiar',
            name='edad',
        ),
    ]
